### ISSUE TITLE
Unsupported conversion character %.

### ISSUE THREAD

**Issue by a1ex-ak** [Aryan20/Logomenu#78]
Error: Unsupported conversion character %.

Stack trace:
  vprintf/<@resource:///org/gnome/gjs/modules/core/_format.js:66:19
  vprintf@resource:///org/gnome/gjs/modules/core/_format.js:13:19
  format@resource:///org/gnome/gjs/modules/script/format.js:28:12
  _init@file:///home/ciso/.local/share/gnome-shell/extensions/logomenu@aryan_k/PrefsLib/adw.js:584:103
  LogoMenuAboutPage@file:///home/ciso/.local/share/gnome-shell/extensions/logomenu@aryan_k/PrefsLib/adw.js:467:48
  fillPreferencesWindow@file:///home/ciso/.local/share/gnome-shell/extensions/logomenu@aryan_k/prefs.js:22:27
  _loadPrefs@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:41:18
  async*_init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:26:14
  ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:17:4
  OpenExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:139:33
  async*LaunchExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:126:14
  _handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:373:35
  _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
  _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34

**Comment by Aryan20** [comment]
Hi!
There was an issue with the translation you did, which triggered the failure. 
I have fixed it but the new release will happen when more changes are there.

**Comment by Aryan20** [comment]
For now, you can download the code and run "make install"

**Comment by a1ex-ak** [comment]
> Hi! There was an issue with the translation you did, which triggered the failure. I have fixed it but the new release will happen when more changes are there.

Tell me where I made a mistake? So as not to repeat it?

**Comment by a1ex-ak** [comment]
> For now, you can download the code and run "make install"

Can you put together a zip file for me? Or tell me how to assemble it?
Thank you

**Comment by a1ex-ak** [comment]
> For now, you can download the code and run "make install"

I downloaded the code but I still get an error

Error: Unsupported conversion character %.

Stack trace:
  vprintf/<@resource:///org/gnome/gjs/modules/core/_format.js:66:19
  vprintf@resource:///org/gnome/gjs/modules/core/_format.js:13:19
  format@resource:///org/gnome/gjs/modules/script/format.js:28:12
  _init@file:///home/ciso/.local/share/gnome-shell/extensions/logomenu@aryan_k/PrefsLib/adw.js:584:103
  LogoMenuAboutPage@file:///home/ciso/.local/share/gnome-shell/extensions/logomenu@aryan_k/PrefsLib/adw.js:467:48
  fillPreferencesWindow@file:///home/ciso/.local/share/gnome-shell/extensions/logomenu@aryan_k/prefs.js:22:27
  _loadPrefs@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:41:18
  async*_init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:26:14
  ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:17:4
  OpenExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:139:33
  async*LaunchExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:126:14
  _handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:373:35
  _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
  _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34

**Comment by Aryan20** [comment]
@a1ex-ak  Ah great!  You can refer https://github.com/Aryan20/Logomenu/commit/f35bb007631b9b995f332b0598340c46b4daa30e for what was wrong with the translation.
